#!/bin/bash -ex

[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.188.0.1"
[[ -z "$GATEWAY" ]] && export GATEWAY="10.188.0.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.188.0.0/16"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.188.150.0:10.188.191.255"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"
export BARE_METAL=true

./profiles/default $1 $2 $3 $4 $5

